### ISSUE TITLE
Vim-Plug Installation Error

### ISSUE THREAD

**Issue by WebGameLinux** [LER0ever/EverVim#5] opened 2017-05-02 09:12 UTC
## Error
![1](https://cloud.githubusercontent.com/assets/19490915/25611786/f815df7c-2f5a-11e7-9472-573f86e63ed5.png)

### Plugins.vim
![2](https://cloud.githubusercontent.com/assets/19490915/25611802/fe840794-2f5a-11e7-8232-0593773e7d8b.png)

**Comment by LER0ever** [comment] 2017-05-03 15:54
Hi, thanks for the report. It seems your vim-plug isn't properly installed. Did you get any error with the powershell script? If no error occured, please check that you have `C:/Users/username/.EverVim/autoload/plug.vim` file (if not, please run the script again as administrator).

**Comment by LER0ever** [comment] 2017-05-04 20:53
I'll close this for now, as setup goes well on my Windows machine. Feel free to reopen if you still have problem with the setup.

**Comment by zouqinxiang** [comment] 2017-05-13 02:15
I also have the same problem,there is no error on my Windows 10 machine when I install plug.vim , but when I open gvim , It show notice: "Unknown function: plug#begin".

**Comment by LER0ever** [comment] 2017-05-13 02:43
For those of you who have problems with vim-plug, could you please check if the `vimfiles` folder in your home directory(`C:\Users\username\vimfiles`) is properly linked to ~/.EverVim? Because I cannot reproduce the bug even on a newly installed virtual machine (Windows 10 Educational 1703 64 bit Build 15063.296)

image of EverVim fresh installation on a Windows 10 virtual machine
![image](https://cloud.githubusercontent.com/assets/10568668/26021878/423fba42-375c-11e7-9a76-0d93af36d76e.png)

**Comment by zouqinxiang** [comment] 2017-05-13 03:36
I have checked vimfiles folder  , it has been linked to ~/.EverVim;
The error image is on my win10 machine.
![gvim_error](https://cloud.githubusercontent.com/assets/3139340/26022175/73f96596-37d0-11e7-95ad-3ac7c2c3c4ad.png)

**Comment by LER0ever** [comment] 2017-05-13 04:02
OK, currently I don't have Windows installed on any of my computers, I'll try to test the installation on multiple editions of Windows 10 after I get back to China (which is about two days later). Leaving it open for now, and sorry for the bug.

**Comment by LER0ever** [comment] 2017-05-15 08:53
It should be fixed by [e8c4a3a](https://github.com/LER0ever/EverVim/commit/e8c4a3a9f0546501fe2f4617a715a03cc28007fa)

The problem is cause by some version of Vim/GVim not recognizing the traditional ~/vimfiles folder. So I changed the soft link to ~/.vim. Sorry for the inconvenience.

Newest screenshot on Windows 7
![image](https://cloud.githubusercontent.com/assets/10568668/26049824/f665be7a-398e-11e7-923e-18eeba5377f8.png)

**Closed as completed by LER0ever** 2017-05-15 08:53 UTC
Labels: bug, help wanted, os-windows, lang-English

**Comment by LER0ever** [comment] 2017-05-15 09:10
Actually, it is fixed by the most recent commit ede486c, which still uses vimfiles for its vimrc and .vim folder for runtime path.
