### ISSUE TITLE
NeoVim Stuck at the first stage of installation

### ISSUE THREAD

**Issue by duytrung** [LER0ever/EverVim#32] opened 2018-03-24 11:45 UTC
I got this error when reinstall the evervim:
```
PS C:\Users\dell\.EverVim> dir


    Directory: C:\Users\dell\.EverVim


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        24-Mar-18  10:03 PM                core
d-----        24-Mar-18  10:03 PM                docs
d-----        24-Mar-18  10:03 PM                plugins
d-----        24-Mar-18  10:03 PM                tools
-a----        24-Mar-18  10:03 PM            365 .EverVim.project.sample
-a----        24-Mar-18  10:03 PM           6198 .EverVim.vimrc.sample
-a----        24-Mar-18  10:03 PM            187 .gitignore
-a----        24-Mar-18  10:03 PM             93 .gitmodules
-a----        24-Mar-18  10:03 PM           1939 Boot-EverVim.ps1
-a----        24-Mar-18  10:03 PM           1123 Boot-EverVim.sh
-a----        24-Mar-18  10:03 PM          10690 LICENSE.md
-a----        24-Mar-18  10:03 PM           5261 README.md
-a----        24-Mar-18  10:03 PM            488 vimrc


PS C:\Users\dell\.EverVim> .\Boot-EverVim.ps1 set-ExecutionPolicy RemoteSigned
Welcome to EverVim, a powerful & modern vim distribution
Booting EverVim ...
Processing files and directories ...


    Directory: C:\Users\dell\.EverVim


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        24-Mar-18  10:05 PM                autoload
d-----        24-Mar-18  10:05 PM                bundle
The system cannot find the file specified.
Soft-Linking Vim/NeoVim Config ...
symbolic link created for C:\Users\dell\vimfiles\ <<===>> C:\Users\dell\.EverVim\
symbolic link created for C:\Users\dell\.vim\ <<===>> C:\Users\dell\.EverVim\
symbolic link created for C:\Users\dell\AppData\Local\nvim\ <<===>> C:\Users\dell\.EverVim\
symbolic link created for C:\Users\dell\.EverVim\init.vim <<===>> C:\Users\dell\.EverVim\vimrc
symbolic link created for C:\Users\dell\.EverVim\ginit.vim <<===>> C:\Users\dell\.EverVim\core\gui.vim
Downloading Vim-Plug ...
All done with the setup.
Now please open up your vim and Type :PlugInstall in your vim to complete the plugin installation


PS C:\Users\dell\.EverVim> nvim
No color theme available, falling back to desert ...
Press ENTER or type command to continue

```

Please advice. Thanks

**Comment by LER0ever** [comment] 2018-03-25 02:46
Hi @duytrung , this is actually a duplicate of #29 and has already been [resolved](https://github.com/LER0ever/EverVim/issues/29#issuecomment-375941064) by now.

**Closed as completed** 2018-03-29 22:53 UTC
